import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

live_config_reload = true

[env]
TERM= "xterm-256color"

[window]
opacity = 0.8
decorations = "None"
blur = true
dynamic_padding = true

[window.padding]
x = 0
y = 0

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
