import = [
  "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

live_config_reload = true

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 12

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
